---
driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
    driver:
      linked_clone: true
suites:
  - name: default
    run_list:
      - recipe[ubuntu_memcache::default]
    verifier:
      inspec_tests:
        - test/recipes
    attributes:
